### ISSUE TITLE
TinyAlu example on Windows - error on class_

### ISSUE THREAD

**Issue by svenka3** [pyuvm/pyuvm#113]
Hi,
  On a Windows 10, running MSYS64 I see error as below:

```python
@pyuvm.test()
class ParallelTest(AluTest.class_):
```
```log
  class ParallelTest(AluTest.class_):
AttributeError: type object 'AluTest' has no attribute 'class_'
```

Removing the class_ from the test seems to fix the issue. Is this some OS-specific issue?

Thanks
Srini

**Comment by raysalemi** [comment]
Is there a typo?  I don’t know why `class_` is in there.

Which example is this, and is it mirrored in the book?

**Comment by raysalemi** [comment]
> Hi,
> 
>   On a Windows 10, running MSYS64 I see error as below:
> 
> 
> 
> ```python
> 
> @pyuvm.test()
> 
> class ParallelTest(AluTest.class_):
> 
> ```
> 
> ```log
> 
>   class ParallelTest(AluTest.class_):
> 
> AttributeError: type object 'AluTest' has no attribute 'class_'
> 
> ```
> 
> 
> 
> Removing the class_ from the test seems to fix the issue. Is this some OS-specific issue?
> 
> 
> 
> Thanks
> 
> Srini

I'm not sure why `class_` is in this example. Which example is this and is the example mirrored in the book?

**Comment by svenka3** [comment]
It is pyuvm/examples/TineyAlu and also in the README.md

See: https://github.com/pyuvm/pyuvm#the-alutest-classes 

Thanks

**Comment by raysalemi** [comment]
Hmm...this is a bug that got introduced at some point.  I'll need to fix it ASAP.

Thank you for letting me know!

**Comment by svenka3** [comment]
Is the fix as simple as knocking that class_ off? I did that and it ran with all PASS.

I can submit a PR if you like (trivial fix anyway)

Thanks

**Comment by raysalemi** [comment]
I think this issue here is that the tip of pyuvm has been modified to work with cocotb 1.7, but you are probably running 1.6.  @ktbarrett, may be able to shed light on this as we've modified the `@pyuvm` decorator to work with 1.7.  This is where the `.class_` reference is coming from.

**Comment by raysalemi** [comment]
It turns out the fix is installing cocotb 1.7 or later.

**Comment by raysalemi** [comment]
If you do a `git pull origin master` now, you should get code without the `.class_` that will work.  Thank you for bringing up this bug!  

Please test it and let me know if it works.

**Comment by svenka3** [comment]
> I think this issue here is that the tip of pyuvm has been modified to work with cocotb 1.7, but you are probably running 1.6. @ktbarrett, may be able to shed light on this as we've modified the `@pyuvm` decorator to work with 1.7. This is where the `.class_` reference is coming from.

I checked my cocotb-config -v, it shows 1.7.1 

I am bit confused now - are you saying with latest Cocotb + pyvum we will have class_ or not have? 

Thanks for looking into this over your weekend, appreciate it!

**Comment by raysalemi** [comment]
> > I think this issue here is that the tip of pyuvm has been modified to work with cocotb 1.7, but you are probably running 1.6. @ktbarrett, may be able to shed light on this as we've modified the `@pyuvm` decorator to work with 1.7. This is where the `.class_` reference is coming from.
> 
> I checked my cocotb-config -v, it shows 1.7.1
> 
> I am bit confused now - are you saying with latest Cocotb + pyvum we will have class_ or not have?
> 
> Thanks for looking into this over your weekend, appreciate it!

We will **not** have `.class_` in the future.

The confusion here is my fault.  @ktbarrett and I discussed this idea, but I didn't realize that it would affect the match between working examples and the book.  Now that I realize this, I have rolled back the change.

**Comment by ktbarrett** [comment]
The roll back has broken the ability to use `TESTCASE` which is why the change was made originally. There is no way to make the code as it stands in the example (I haven't seen the book yet) and `TESTCASE` work at the same time. So it's broke and cannot be fixed with the way cocotb is written currently. The only way forward is to use `COCOTB_CUSTOM_ENTRY` which will require replicating most of the cocotb bootstrap code and replacing the regression manager with a better one.

**Comment by raysalemi** [comment]
Yup.  That was the tradeoff.  The workaround is to create a cocotb test
that runs pyuvm as in the old days.

**Comment by raysalemi** [comment]
This is fixed in release 2.9.0.

**Comment by svenka3** [comment]
Tried a fresh clone and it works out-of-the box, thanks for the fix.
